// ============================================================================
// Shared Excel Constants - Single Source of Truth
// ============================================================================

/**
 * Excel sheet names (must match exactly between export and import)
 */
export const SHEET_NAMES = {
  PARTS: "Parts",
  VEHICLE_APPLICATIONS: "Vehicle Applications",
  ALIASES: "Vehicle Aliases",
} as const;

/**
 * Excel column headers (friendly names without underscores)
 * These appear in the Excel file header row (Row 2)
 */
export const COLUMN_HEADERS = {
  // Parts sheet
  PARTS: {
    ACR_SKU: "ACR SKU",
    STATUS: "Status",
    PART_TYPE: "Part Type",
    POSITION_TYPE: "Position",
    ABS_TYPE: "ABS Type",
    BOLT_PATTERN: "Bolt Pattern",
    DRIVE_TYPE: "Drive Type",
    SPECIFICATIONS: "Specifications",
    // Cross-reference brand columns — just brand names
    NATIONAL_SKUS: "National",
    ATV_SKUS: "ATV",
    SYD_SKUS: "SYD",
    TMK_SKUS: "TMK",
    GROB_SKUS: "GROB",
    RACE_SKUS: "RACE",
    OEM_SKUS: "OEM",
    OEM_2_SKUS: "OEM_2",
    GMB_SKUS: "GMB",
    GSP_SKUS: "GSP",
    FAG_SKUS: "FAG",
    // Image URL columns
    IMAGE_URL_FRONT: "Image URL Front",
    IMAGE_URL_BACK: "Image URL Back",
    IMAGE_URL_TOP: "Image URL Top",
    IMAGE_URL_OTHER: "Image URL Other",
    VIEWER_360_STATUS: "360 Viewer",
    // Formula-driven validation
    ERRORS: "Errors",
  },

  // Vehicle Applications sheet
  VEHICLE_APPLICATIONS: {
    ACR_SKU: "ACR SKU",
    STATUS: "Status",
    MAKE: "Make",
    MODEL: "Model",
    START_YEAR: "Start Year",
    END_YEAR: "End Year",
    ERRORS: "Errors",
  },

  // Vehicle Aliases sheet
  ALIASES: {
    ALIAS: "Alias",
    CANONICAL_NAME: "Canonical Name",
    ALIAS_TYPE: "Type",
    STATUS: "Status",
    ERRORS: "Errors",
  },
} as const;

/**
 * Object property names (snake_case)
 * These are the keys used in JavaScript/TypeScript objects
 */
export const PROPERTY_NAMES = {
  // Parts
  PARTS: {
    ACR_SKU: "acr_sku",
    STATUS: "status",
    PART_TYPE: "part_type",
    POSITION_TYPE: "position_type",
    ABS_TYPE: "abs_type",
    BOLT_PATTERN: "bolt_pattern",
    DRIVE_TYPE: "drive_type",
    SPECIFICATIONS: "specifications",
    // Cross-reference brand columns
    NATIONAL_SKUS: "national_skus",
    ATV_SKUS: "atv_skus",
    SYD_SKUS: "syd_skus",
    TMK_SKUS: "tmk_skus",
    GROB_SKUS: "grob_skus",
    RACE_SKUS: "race_skus",
    OEM_SKUS: "oem_skus",
    OEM_2_SKUS: "oem_2_skus",
    GMB_SKUS: "gmb_skus",
    GSP_SKUS: "gsp_skus",
    FAG_SKUS: "fag_skus",
    // Image URL columns
    IMAGE_URL_FRONT: "image_url_front",
    IMAGE_URL_BACK: "image_url_back",
    IMAGE_URL_TOP: "image_url_top",
    IMAGE_URL_OTHER: "image_url_other",
    VIEWER_360_STATUS: "viewer_360_status",
    ERRORS: "errors",
  },

  // Vehicle Applications
  VEHICLE_APPLICATIONS: {
    ACR_SKU: "acr_sku",
    STATUS: "status",
    MAKE: "make",
    MODEL: "model",
    START_YEAR: "start_year",
    END_YEAR: "end_year",
    ERRORS: "errors",
  },

  // Vehicle Aliases
  ALIASES: {
    ALIAS: "alias",
    CANONICAL_NAME: "canonical_name",
    ALIAS_TYPE: "alias_type",
    STATUS: "status",
    ERRORS: "errors",
  },
} as const;

/**
 * Column widths for Excel export
 */
export const COLUMN_WIDTHS = {
  // Parts sheet
  PARTS: {
    ACR_SKU: 15,
    STATUS: 12,
    PART_TYPE: 20,
    POSITION_TYPE: 15,
    ABS_TYPE: 15,
    BOLT_PATTERN: 15,
    DRIVE_TYPE: 15,
    SPECIFICATIONS: 40,
    NATIONAL_SKUS: 25,
    ATV_SKUS: 25,
    SYD_SKUS: 25,
    TMK_SKUS: 25,
    GROB_SKUS: 25,
    RACE_SKUS: 25,
    OEM_SKUS: 25,
    OEM_2_SKUS: 25,
    GMB_SKUS: 25,
    GSP_SKUS: 25,
    FAG_SKUS: 25,
    IMAGE_URL_FRONT: 25,
    IMAGE_URL_BACK: 25,
    IMAGE_URL_TOP: 25,
    IMAGE_URL_OTHER: 25,
    VIEWER_360_STATUS: 18,
    ERRORS: 30,
  },

  // Vehicle Applications sheet
  VEHICLE_APPLICATIONS: {
    ACR_SKU: 15,
    STATUS: 12,
    MAKE: 15,
    MODEL: 20,
    START_YEAR: 12,
    END_YEAR: 12,
    ERRORS: 30,
  },

  // Vehicle Aliases sheet
  ALIASES: {
    ALIAS: 20,
    CANONICAL_NAME: 25,
    ALIAS_TYPE: 12,
    STATUS: 12,
    ERRORS: 30,
  },
} as const;

/**
 * Computed columns auto-generated by database triggers — NOT exported to Excel
 */
export const HIDDEN_COMPUTED_COLUMNS = [
  "acr_sku_normalized",
  "competitor_sku_normalized",
  "created_at",
  "updated_at",
] as const;

/**
 * File validation constants
 */
export const FILE_VALIDATION = {
  VALID_EXTENSIONS: [".xlsx", ".xls"] as const,
  VALID_MIME_TYPES: [
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-excel",
  ] as const,
  MAX_FILE_SIZE_MB: 50,
  MAX_FILE_SIZE_BYTES: 50 * 1024 * 1024,
} as const;

// ============================================================================
// Cross-Reference Brand Columns & Image URLs
// ============================================================================

/**
 * Brand column property name → database competitor_brand value mapping
 * Used to convert Excel column data to cross_references records
 */
export const BRAND_COLUMN_MAP: Record<string, string> = {
  national_skus: "NATIONAL",
  atv_skus: "ATV",
  syd_skus: "SYD",
  tmk_skus: "TMK",
  grob_skus: "GROB",
  race_skus: "RACE",
  oem_skus: "OEM",
  oem_2_skus: "OEM 2",
  gmb_skus: "GMB",
  gsp_skus: "GSP",
  fag_skus: "FAG",
};

/**
 * All brand column property names (for iteration)
 */
export const BRAND_COLUMN_NAMES = Object.keys(BRAND_COLUMN_MAP);

/**
 * Image URL column property name → view_type value mapping
 * Used to convert Excel column data to part_images records
 */
export const IMAGE_VIEW_TYPE_MAP: Record<string, string> = {
  image_url_front: "front",
  image_url_back: "back",
  image_url_top: "top",
  image_url_other: "other",
};

/**
 * All image URL column property names (for iteration)
 */
export const IMAGE_URL_COLUMN_NAMES = Object.keys(IMAGE_VIEW_TYPE_MAP);

/**
 * Delete marker for explicit cross-reference deletion (ML-style safe delete)
 * Usage in Excel: "[DELETE]SKU123" marks SKU123 for deletion
 */
export const DELETE_MARKER = "[DELETE]";

/**
 * Mapping of simplified brand column headers to property names
 * Used for import when headers don't have "_SKUs" suffix
 */
const BRAND_HEADER_TO_PROPERTY: Record<string, string> = {
  national: "national_skus",
  atv: "atv_skus",
  syd: "syd_skus",
  tmk: "tmk_skus",
  grob: "grob_skus",
  race: "race_skus",
  oem: "oem_skus",
  oem_2: "oem_2_skus",
  gmb: "gmb_skus",
  gsp: "gsp_skus",
  fag: "fag_skus",
};

/**
 * Mapping of friendly column headers (without underscores) to property names
 * Used for import when headers use spaces instead of underscores
 */
const FRIENDLY_HEADER_TO_PROPERTY: Record<string, string> = {
  // Part Information (friendly → property) — English
  "acr sku": "acr_sku",
  status: "status",
  "part type": "part_type",
  position: "position_type",
  "abs type": "abs_type",
  "bolt pattern": "bolt_pattern",
  "drive type": "drive_type",
  specifications: "specifications",
  // Image columns (friendly → property) — English
  "image url front": "image_url_front",
  "image url back": "image_url_back",
  "image url top": "image_url_top",
  "image url other": "image_url_other",
  "360 viewer": "viewer_360_status",
  // Vehicle Applications (friendly → property) — English
  make: "make",
  model: "model",
  "start year": "start_year",
  "end year": "end_year",
  // Aliases (friendly → property) — English
  "canonical name": "canonical_name",
  type: "alias_type",
  // Shared columns
  errors: "errors",

  // --- Spanish headers (Mexican auto parts industry) ---
  // Parts sheet
  estado: "status",
  "tipo de parte": "part_type",
  "posición": "position_type",
  posicion: "position_type", // unaccented variant
  "tipo de abs": "abs_type",
  "patrón de birlos": "bolt_pattern",
  "patron de birlos": "bolt_pattern", // unaccented variant
  "tipo de tracción": "drive_type",
  "tipo de traccion": "drive_type", // unaccented variant
  especificaciones: "specifications",
  // Image columns — Spanish
  "url imagen frente": "image_url_front",
  "url imagen atrás": "image_url_back",
  "url imagen atras": "image_url_back", // unaccented variant
  "url imagen arriba": "image_url_top",
  "url imagen otra": "image_url_other",
  "visor 360": "viewer_360_status",
  // Vehicle Applications — Spanish
  marca: "make",
  modelo: "model",
  "año inicio": "start_year",
  "ano inicio": "start_year", // unaccented variant
  "año fin": "end_year",
  "ano fin": "end_year", // unaccented variant
  // Aliases — Spanish
  "nombre canónico": "canonical_name",
  "nombre canonico": "canonical_name", // unaccented variant
  tipo: "alias_type",
  errores: "errors",
};

/**
 * Helper function to convert column header to property name
 * Supports both old format (with underscores) and new format (with spaces)
 *
 * Examples:
 * - Old: "ACR_SKU" → "acr_sku", "Part_Type" → "part_type"
 * - New: "ACR SKU" → "acr_sku", "Part Type" → "part_type"
 * - Brand: "National" → "national_skus"
 */
export function headerToPropertyName(header: string): string {
  const lowercased = header.toLowerCase();

  // Check friendly header mapping first (headers with spaces)
  if (FRIENDLY_HEADER_TO_PROPERTY[lowercased]) {
    return FRIENDLY_HEADER_TO_PROPERTY[lowercased];
  }

  // Check simplified brand column headers (e.g., "National" → "national_skus")
  if (BRAND_HEADER_TO_PROPERTY[lowercased]) {
    return BRAND_HEADER_TO_PROPERTY[lowercased];
  }

  // Fallback: lowercase and normalize separators
  return lowercased.replace(/\s+/g, "_").replace(/_+/g, "_");
}

/**
 * Helper function to convert property name to column header
 * Example: "acr_sku" → "ACR_SKU", "part_type" → "Part_Type"
 */
export function propertyNameToHeader(propertyName: string): string {
  return propertyName
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("_");
}

/**
 * Cross-reference SKU delimiter - semicolon is the canonical delimiter
 */
export const CROSS_REF_DELIMITER = ";";

/**
 * Result of splitting cross-reference SKUs
 */
export interface SplitCrossRefResult {
  /** The individual SKUs after splitting */
  skus: string[];
  /** Whether the original value contained space-delimited SKUs (legacy format) */
  hadSpaceDelimiters: boolean;
}

/**
 * Split cross-reference SKUs from a cell value.
 * Uses semicolon as the only delimiter.
 *
 * SKU values may contain spaces (e.g., "713 6493 80" is a single SKU value).
 * Only semicolons separate multiple SKUs in a cell.
 *
 * @param value - The raw cell value containing one or more SKUs
 * @returns Object with split SKUs and whether legacy space delimiters were found
 */
export function splitCrossRefSkus(
  value: string | undefined | null
): SplitCrossRefResult {
  if (!value || value.trim() === "") {
    return { skus: [], hadSpaceDelimiters: false };
  }

  const trimmedValue = value.trim();

  // Split on semicolons only — spaces within SKUs are preserved
  const skus = trimmedValue
    .split(";")
    .map((s) => s.trim())
    .filter((s) => s !== "");

  return { skus, hadSpaceDelimiters: false };
}

// ----------------------------------------------------------------------------
// Column Definitions (for Export Service)
// ----------------------------------------------------------------------------

/**
 * Parts sheet column definitions
 * Single source of truth for column structure
 *
 * Note: Not using 'as const' because ExcelJS expects mutable arrays
 */
export const PARTS_COLUMNS = [
  {
    header: COLUMN_HEADERS.PARTS.ACR_SKU,
    key: PROPERTY_NAMES.PARTS.ACR_SKU,
    width: COLUMN_WIDTHS.PARTS.ACR_SKU,
  },
  {
    header: COLUMN_HEADERS.PARTS.STATUS,
    key: PROPERTY_NAMES.PARTS.STATUS,
    width: COLUMN_WIDTHS.PARTS.STATUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.PART_TYPE,
    key: PROPERTY_NAMES.PARTS.PART_TYPE,
    width: COLUMN_WIDTHS.PARTS.PART_TYPE,
  },
  {
    header: COLUMN_HEADERS.PARTS.POSITION_TYPE,
    key: PROPERTY_NAMES.PARTS.POSITION_TYPE,
    width: COLUMN_WIDTHS.PARTS.POSITION_TYPE,
  },
  {
    header: COLUMN_HEADERS.PARTS.ABS_TYPE,
    key: PROPERTY_NAMES.PARTS.ABS_TYPE,
    width: COLUMN_WIDTHS.PARTS.ABS_TYPE,
  },
  {
    header: COLUMN_HEADERS.PARTS.BOLT_PATTERN,
    key: PROPERTY_NAMES.PARTS.BOLT_PATTERN,
    width: COLUMN_WIDTHS.PARTS.BOLT_PATTERN,
  },
  {
    header: COLUMN_HEADERS.PARTS.DRIVE_TYPE,
    key: PROPERTY_NAMES.PARTS.DRIVE_TYPE,
    width: COLUMN_WIDTHS.PARTS.DRIVE_TYPE,
  },
  {
    header: COLUMN_HEADERS.PARTS.SPECIFICATIONS,
    key: PROPERTY_NAMES.PARTS.SPECIFICATIONS,
    width: COLUMN_WIDTHS.PARTS.SPECIFICATIONS,
  },
  // Cross-reference brand columns — semicolon-separated SKUs
  {
    header: COLUMN_HEADERS.PARTS.NATIONAL_SKUS,
    key: PROPERTY_NAMES.PARTS.NATIONAL_SKUS,
    width: COLUMN_WIDTHS.PARTS.NATIONAL_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.ATV_SKUS,
    key: PROPERTY_NAMES.PARTS.ATV_SKUS,
    width: COLUMN_WIDTHS.PARTS.ATV_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.SYD_SKUS,
    key: PROPERTY_NAMES.PARTS.SYD_SKUS,
    width: COLUMN_WIDTHS.PARTS.SYD_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.TMK_SKUS,
    key: PROPERTY_NAMES.PARTS.TMK_SKUS,
    width: COLUMN_WIDTHS.PARTS.TMK_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.GROB_SKUS,
    key: PROPERTY_NAMES.PARTS.GROB_SKUS,
    width: COLUMN_WIDTHS.PARTS.GROB_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.RACE_SKUS,
    key: PROPERTY_NAMES.PARTS.RACE_SKUS,
    width: COLUMN_WIDTHS.PARTS.RACE_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.OEM_SKUS,
    key: PROPERTY_NAMES.PARTS.OEM_SKUS,
    width: COLUMN_WIDTHS.PARTS.OEM_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.OEM_2_SKUS,
    key: PROPERTY_NAMES.PARTS.OEM_2_SKUS,
    width: COLUMN_WIDTHS.PARTS.OEM_2_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.GMB_SKUS,
    key: PROPERTY_NAMES.PARTS.GMB_SKUS,
    width: COLUMN_WIDTHS.PARTS.GMB_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.GSP_SKUS,
    key: PROPERTY_NAMES.PARTS.GSP_SKUS,
    width: COLUMN_WIDTHS.PARTS.GSP_SKUS,
  },
  {
    header: COLUMN_HEADERS.PARTS.FAG_SKUS,
    key: PROPERTY_NAMES.PARTS.FAG_SKUS,
    width: COLUMN_WIDTHS.PARTS.FAG_SKUS,
  },
  // Image URL columns
  {
    header: COLUMN_HEADERS.PARTS.IMAGE_URL_FRONT,
    key: PROPERTY_NAMES.PARTS.IMAGE_URL_FRONT,
    width: COLUMN_WIDTHS.PARTS.IMAGE_URL_FRONT,
  },
  {
    header: COLUMN_HEADERS.PARTS.IMAGE_URL_BACK,
    key: PROPERTY_NAMES.PARTS.IMAGE_URL_BACK,
    width: COLUMN_WIDTHS.PARTS.IMAGE_URL_BACK,
  },
  {
    header: COLUMN_HEADERS.PARTS.IMAGE_URL_TOP,
    key: PROPERTY_NAMES.PARTS.IMAGE_URL_TOP,
    width: COLUMN_WIDTHS.PARTS.IMAGE_URL_TOP,
  },
  {
    header: COLUMN_HEADERS.PARTS.IMAGE_URL_OTHER,
    key: PROPERTY_NAMES.PARTS.IMAGE_URL_OTHER,
    width: COLUMN_WIDTHS.PARTS.IMAGE_URL_OTHER,
  },
  {
    header: COLUMN_HEADERS.PARTS.VIEWER_360_STATUS,
    key: PROPERTY_NAMES.PARTS.VIEWER_360_STATUS,
    width: COLUMN_WIDTHS.PARTS.VIEWER_360_STATUS,
  },
  // Errors column (formula-driven validation, last column)
  {
    header: COLUMN_HEADERS.PARTS.ERRORS,
    key: PROPERTY_NAMES.PARTS.ERRORS,
    width: COLUMN_WIDTHS.PARTS.ERRORS,
  },
];

/**
 * Vehicle Applications sheet column definitions
 */
export const VEHICLE_APPLICATIONS_COLUMNS = [
  {
    header: COLUMN_HEADERS.VEHICLE_APPLICATIONS.ACR_SKU,
    key: PROPERTY_NAMES.VEHICLE_APPLICATIONS.ACR_SKU,
    width: COLUMN_WIDTHS.VEHICLE_APPLICATIONS.ACR_SKU,
  },
  {
    header: COLUMN_HEADERS.VEHICLE_APPLICATIONS.STATUS,
    key: PROPERTY_NAMES.VEHICLE_APPLICATIONS.STATUS,
    width: COLUMN_WIDTHS.VEHICLE_APPLICATIONS.STATUS,
  },
  {
    header: COLUMN_HEADERS.VEHICLE_APPLICATIONS.MAKE,
    key: PROPERTY_NAMES.VEHICLE_APPLICATIONS.MAKE,
    width: COLUMN_WIDTHS.VEHICLE_APPLICATIONS.MAKE,
  },
  {
    header: COLUMN_HEADERS.VEHICLE_APPLICATIONS.MODEL,
    key: PROPERTY_NAMES.VEHICLE_APPLICATIONS.MODEL,
    width: COLUMN_WIDTHS.VEHICLE_APPLICATIONS.MODEL,
  },
  {
    header: COLUMN_HEADERS.VEHICLE_APPLICATIONS.START_YEAR,
    key: PROPERTY_NAMES.VEHICLE_APPLICATIONS.START_YEAR,
    width: COLUMN_WIDTHS.VEHICLE_APPLICATIONS.START_YEAR,
  },
  {
    header: COLUMN_HEADERS.VEHICLE_APPLICATIONS.END_YEAR,
    key: PROPERTY_NAMES.VEHICLE_APPLICATIONS.END_YEAR,
    width: COLUMN_WIDTHS.VEHICLE_APPLICATIONS.END_YEAR,
  },
  {
    header: COLUMN_HEADERS.VEHICLE_APPLICATIONS.ERRORS,
    key: PROPERTY_NAMES.VEHICLE_APPLICATIONS.ERRORS,
    width: COLUMN_WIDTHS.VEHICLE_APPLICATIONS.ERRORS,
  },
];

/**
 * Vehicle Aliases sheet column definitions
 */
export const ALIASES_COLUMNS = [
  {
    header: COLUMN_HEADERS.ALIASES.ALIAS,
    key: PROPERTY_NAMES.ALIASES.ALIAS,
    width: COLUMN_WIDTHS.ALIASES.ALIAS,
  },
  {
    header: COLUMN_HEADERS.ALIASES.CANONICAL_NAME,
    key: PROPERTY_NAMES.ALIASES.CANONICAL_NAME,
    width: COLUMN_WIDTHS.ALIASES.CANONICAL_NAME,
  },
  {
    header: COLUMN_HEADERS.ALIASES.ALIAS_TYPE,
    key: PROPERTY_NAMES.ALIASES.ALIAS_TYPE,
    width: COLUMN_WIDTHS.ALIASES.ALIAS_TYPE,
  },
  {
    header: COLUMN_HEADERS.ALIASES.STATUS,
    key: PROPERTY_NAMES.ALIASES.STATUS,
    width: COLUMN_WIDTHS.ALIASES.STATUS,
  },
  {
    header: COLUMN_HEADERS.ALIASES.ERRORS,
    key: PROPERTY_NAMES.ALIASES.ERRORS,
    width: COLUMN_WIDTHS.ALIASES.ERRORS,
  },
];

// ----------------------------------------------------------------------------
// Workflow Status Mappings
// ----------------------------------------------------------------------------

/**
 * Map Spanish Excel status values to database enum values
 * Supports both Spanish and English inputs (case-insensitive)
 */
export const WORKFLOW_STATUS_MAP: Record<string, string> = {
  activo: "ACTIVE",
  active: "ACTIVE",
  inactivo: "INACTIVE",
  inactive: "INACTIVE",
  eliminar: "DELETE",
  delete: "DELETE",
};

/**
 * Map database enum values to Spanish display values for Excel export
 */
export const WORKFLOW_STATUS_DISPLAY: Record<string, string> = {
  ACTIVE: "Activo",
  INACTIVE: "Inactivo",
  DELETE: "Eliminar",
};

// ----------------------------------------------------------------------------
// Spanish Header Map (for locale-aware export + test builder)
// ----------------------------------------------------------------------------

/**
 * Maps property name → Spanish column header text
 * Used by ExcelExportService for locale-aware exports and TestWorkbookBuilder for i18n tests.
 * Brand columns (National, ATV, SYD, etc.) are identical in both languages.
 */
export const SPANISH_HEADER_MAP: Record<string, string> = {
  // Parts sheet
  status: "Estado",
  part_type: "Tipo de Parte",
  position_type: "Posición",
  abs_type: "Tipo de ABS",
  bolt_pattern: "Patrón de Birlos",
  drive_type: "Tipo de Tracción",
  specifications: "Especificaciones",
  // Image columns
  image_url_front: "URL Imagen Frente",
  image_url_back: "URL Imagen Atrás",
  image_url_top: "URL Imagen Arriba",
  image_url_other: "URL Imagen Otra",
  viewer_360_status: "Visor 360",
  errors: "Errores",
  // Vehicle Applications sheet
  make: "Marca",
  model: "Modelo",
  start_year: "Año Inicio",
  end_year: "Año Fin",
  // Aliases sheet
  canonical_name: "Nombre Canónico",
  alias_type: "Tipo",
};
